add pipeline

diff --git a/bin/unit_test b/bin/unit_test
--- a/bin/unit_test
+++ b/bin/unit_test
@@ -1,41 +1,28 @@
-
-  #!/bin/bash
+#!/bin/bash
   
-  (
-    set -e
+(
+  set -e
 
-    base=$( cd "$( dirname "$( dirname "$0" )")" && pwd )
-    base_gopath=$( cd $base/../.. && pwd )
-    export GOPATH=$base_gopath:$GOPATH
+  base=$( cd "$( dirname "$( dirname "$0" )")" && pwd )
+  base_gopath=$( cd $base/../.. && pwd )
+  export GOPATH=$base_gopath:$GOPATH
 
-    go get golang.org/x/tools/cmd/cover
-    go get github.com/modocache/gover
-    go get github.com/mattn/goveralls
+  function printStatus {
+    if [ $? -eq 0 ]; then
+      echo -e "\nSWEET SUITE SUCCESS"
+    else
+      echo -e "\nSUITE FAILURE"
+    fi
+  }
 
-    function printStatus {
-      if [ $? -eq 0 ]; then
-          echo -e "\nSWEET SUITE SUCCESS"
-      else
-          echo -e "\nSUITE FAILURE"
-      fi
-    }
+  trap printStatus EXIT
 
-    trap printStatus EXIT
+  echo -e "\n Cleaning build artifacts..."
+  go clean
 
-    echo -e "\n Cleaning build artifacts..."
-    go clean
+  echo -e "\n Formatting packages..."
+  go fmt $(go list ./... | grep -v /vendor/)
 
-    echo -e "\n Formatting packages..."
-    go fmt $(go list ./... | grep -v /vendor/)
-
-    echo -e "\n Unit Testing packages:"
-    ginkgo -r -p -cover $base -skipPackage $base/vendor
-
-    echo -e "\n Gathering cover profiles and send to coveralls.io..."
-    # Need check env COVERALLS_TOKEN
-    gover $base $base/gover.coverprofile
-    goveralls -coverprofile=gover.coverprofile -service=travis-pro -repotoken=$COVERALLS_TOKEN -show
-
-    echo -e "\n Vetting packages for potential issues..."
-    go tool vet $base/*.go
-  )
+  echo -e "\n Unit Testing packages:"
+  ginkgo -r -p -cover $base -skipPackage $base/vendor
+)
